-- 2. Edit history
-- History
CREATE TABLE document_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	text LONGTEXT NULL DEFAULT NULL,
	json JSON NULL DEFAULT NULL,
	delta LONGBLOB NULL DEFAULT NULL,
	edit_comment VARCHAR(1000),
	is_minor TINYINT(1) NOT NULL DEFAULT 0,
	document_id BIGINT UNSIGNED NOT NULL,
	usercode VARCHAR(8) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);