<?php

/* public */
define('DB_SERVER_PUBLIC', '*SERVER_VALUE*');
define('DB_USERNAME_PUBLIC', '*USERNAME_VALUE*');
define('DB_PASSWORD_PUBLIC', '*PASSWORD_VALUE*');
define('DB_NAME_PUBLIC', '*DATABASE_NAME_VALUE*');

/* personal */
define('DB_SERVER_PERSONAL', '*SERVER_VALUE*');
define('DB_USERNAME_PERSONAL', '*USERNAME_VALUE*');
define('DB_PASSWORD_PERSONAL', '*PASSWORD_VALUE*');
define('DB_NAME_PERSONAL', '*DATABASE_NAME_VALUE*');

/* private */
define('DB_SERVER_PRIVATE', '*SERVER_VALUE*');
define('DB_USERNAME_PRIVATE', '*USERNAME_VALUE*');
define('DB_PASSWORD_PRIVATE', '*PASSWORD_VALUE*');
define('DB_NAME_PRIVATE', '*DATABASE_NAME_VALUE*');

/* documentation */
define('DB_SERVER_DOCUMENTATION', '*SERVER_VALUE*');
define('DB_USERNAME_DOCUMENTATION', '*USERNAME_VALUE*');
define('DB_PASSWORD_DOCUMENTATION', '*PASSWORD_VALUE*');
define('DB_NAME_DOCUMENTATION', '*DATABASE_NAME_VALUE*');

?>
