<?php

/* public */
define('DB_SERVER_PUBLIC', '[REDACTED]');
define('DB_USERNAME_PUBLIC', '[REDACTED]');
define('DB_PASSWORD_PUBLIC', '[REDACTED]');
define('DB_NAME_PUBLIC', '[REDACTED]');

/* personal */
define('DB_SERVER_PERSONAL', '[REDACTED]');
define('DB_USERNAME_PERSONAL', '[REDACTED]');
define('DB_PASSWORD_PERSONAL', '[REDACTED]');
define('DB_NAME_PERSONAL', '[REDACTED]');

/* private */
define('DB_SERVER_PRIVATE', '[REDACTED]');
define('DB_USERNAME_PRIVATE', '[REDACTED]');
define('DB_PASSWORD_PRIVATE', '[REDACTED]');
define('DB_NAME_PRIVATE', '[REDACTED]');

/* documentation */
define('DB_SERVER_DOCUMENTATION', '[REDACTED]');
define('DB_USERNAME_DOCUMENTATION', '[REDACTED]');
define('DB_PASSWORD_DOCUMENTATION', '[REDACTED]');
define('DB_NAME_DOCUMENTATION', '[REDACTED]');

?>
